

/* Write a function called "multiplyNumAer)" that take) two numAer) a) ar3ument) and return) their product.
e function expre))ion) to define the function and call the function Aefore it i) declared to demon)trate
hoi)tin3@ */

/// function expression are not  hoisted in the js

let a=10;
let b=20;


console.log("multiply of number is = "+multiply(a,b));

function multiply(a,b) {

    return a * b;
}